import { Injectable } from '@angular/core';
import { Restaurant } from '../models/restaurant.model';

@Injectable({
  providedIn: 'root'
})
export class RestaurantDataService {

  private restaurants: Restaurant[] = [
    {
      name: "Kliška Tvrđava",
      address: "Kliška tvrđava",
      city: "Klis",
      category: "Tvrđava",
      tags: "jjj",
      hours: { sunday: "12:00-00:00", monday: "12:00-00:00", tuesday: "12:00-00:00", wednesday: "12:00-00:00", thursday: "12:00-00:00", friday: "12:00-00:00", saturday: "12:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://www.tvrdavaklis.com/",
      gPlaceId: ""
    },
    {
      name: "Pizzeria Bepina",
      address: "Makarska ulica 16",
      city: "Split",
      category: "Pizzeria",
      tags: "",
      hours: { sunday: "12:00-22:00", monday: "09:00-23:00", tuesday: "09:00-23:00", wednesday: "09:00-23:00", thursday: "09:00-23:00", friday: "09:00-23:00", saturday: "09:00-23:00" },
      maxCapacity: 50,
      description: "<p><strong>Pizzeria Bepina: Authentic Italian Pizza</strong></p>\n\n<p>Craving pizza in Split? Bepina delivers. Enjoy classic and creative pizzas with fresh ingredients. Perfect crust, delicious toppings. More than just pizza on the menu too.</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/bepina",
      gPlaceId: ""
    },
    {
      name: "Konoba Teranino",
      address: "Ulica Širina Filipa Grabovca 1",
      city: "Split",
      category: "Restoran",
      tags: "",
      hours: { sunday: "12:00-00:00", monday: "12:00-00:00", tuesday: "12:00-00:00", wednesday: "12:00-00:00", thursday: "12:00-00:00", friday: "12:00-00:00", saturday: "12:00-00:00" },
      maxCapacity: 99,
      description: "<p>Mediterranean cuisine in the heart of Split and Diocletian&rsquo;s Palace! Come and visit us.</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/teranino",
      gPlaceId: ""
    },
    {
      name: "Stari Kapetan",
      address: "Šetalište Kneza Domagoja 8",
      city: "Orebić",
      category: "Restaurant",
      tags: "Turistička zanimljivost",
      hours: { sunday: "07:30-23:00", monday: "07:30-23:00", tuesday: "07:30-23:00", wednesday: "07:30-23:00", thursday: "07:30-23:00", friday: "07:30-23:00", saturday: "07:30-23:00" },
      maxCapacity: 99,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/starikapetan",
      gPlaceId: ""
    },
    {
      name: "Jerolim Hvar",
      address: "Fabrika 32",
      city: "Hvar",
      category: "Restaurant",
      tags: "Fish and meat restaurant",
      hours: { sunday: "10:00-00:00", monday: "10:00-00:00", tuesday: "10:00-00:00", wednesday: "10:00-00:00", thursday: "10:00-00:00", friday: "10:00-00:00", saturday: "10:00-00:00" },
      maxCapacity: 99,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/jerolim",
      gPlaceId: ""
    },
    {
      name: "Testni restoran",
      address: "Osječka ul",
      city: "Split",
      category: "Restaurant",
      tags: "",
      hours: { sunday: "08:00-23:00", monday: "08:00-23:00", tuesday: "08:00-23:00", wednesday: "08:00-23:00", thursday: "08:00-23:00", friday: "08:00-23:00", saturday: "08:00-23:00" },
      maxCapacity: 500,
      description: "",
      bookingLink: "www.kesovija.com",
      gPlaceId: ""
    },
    {
      name: "Crew Bar Split",
      address: "Ul. Sv. Petra starog 15",
      city: "Split",
      category: "",
      tags: "",
      hours: { sunday: "18:00-02:00", monday: "18:00-02:00", tuesday: "18:00-02:00", wednesday: "18:00-02:00", thursday: "18:00-02:00", friday: "18:00-02:00", saturday: "18:00-02:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/CrewBarSplit",
      gPlaceId: ""
    },
    {
      name: "Focus Trogir",
      address: "Obrov 5",
      city: "Trogir",
      category: "Restaurant",
      tags: "Restaurant",
      hours: { sunday: "08:00-00:00", monday: "08:00-00:00", tuesday: "08:00-00:00", wednesday: "08:00-00:00", thursday: "08:00-00:00", friday: "08:00-00:00", saturday: "08:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/focustrogir",
      gPlaceId: ""
    },
    {
      name: "Restaurant PIER",
      address: "Senjska 2",
      city: "Split",
      category: "Restaurant",
      tags: "",
      hours: { sunday: "11:00-00:00", monday: "11:00-00:00", tuesday: "11:00-00:00", wednesday: "11:00-00:00", thursday: "11:00-00:00", friday: "11:00-00:00", saturday: "11:00-00:00" },
      maxCapacity: 50,
      description: "<p>Our concept is a bistro restaurant with a fusion of traditional and modern food, and our &agrave; la carte menu will satisfy everyone, from meat and fish lovers to special burgers, pizza and pasta, and original desserts.</p>\n\n<p>The restaurant is located in Split, Croatia, at Senjska 2, on the beautiful &Scaron;perun square, with a capacity of 26 people in the interior and 12 in the exterior.</p>\n\n<p>The menu was prepared by a long-time chef and contains a combination of Dalmatian and Mediterranean flavors that promise to delight even the pickiest palates. The elegant ambience provides a sophisticated and inviting atmosphere, creating the perfect environment for all kinds of gatherings.</p>\n\n<p>In our desire to be the best, we offer a variety of flexible packages to suit the needs of your agency and guests, including three-, four- and even ten-course meals, personalized menus and accommodation according to dietary preferences.</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/pier",
      gPlaceId: ""
    },
    {
      name: "Focus Kastela",
      address: "Vukovarska ulica 2",
      city: "Kaštel Stari",
      category: "Restaurant",
      tags: "",
      hours: { sunday: "07:00-00:00", monday: "07:00-00:00", tuesday: "07:00-00:00", wednesday: "07:00-00:00", thursday: "07:00-00:00", friday: "07:00-00:00", saturday: "07:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/focuskastela",
      gPlaceId: ""
    },
    {
      name: "Bistro Largo Korčula",
      address: "Svete Barbare 3",
      city: "Korčula",
      category: "Restoran",
      tags: "Restoran morske hrane, Restoran s jelima s roštilja, Restoran za doručke",
      hours: { sunday: "10:00-00:00", monday: "10:00-00:00", tuesday: "10:00-00:00", wednesday: "10:00-00:00", thursday: "10:00-00:00", friday: "10:00-00:00", saturday: "10:00-00:00" },
      maxCapacity: 110,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/largo",
      gPlaceId: ""
    },
    {
      name: "Konoba \"Marco Polo\" Old Town Korcula",
      address: "Ulica Jakova Baničevića 9",
      city: "Korčula",
      category: "Istočnoeuropski restoran",
      tags: "Europski restoran,Restoran,Restoran morske hrane",
      hours: { sunday: "17:00-00:00", monday: "17:00-00:00", tuesday: "17:00-00:00", wednesday: "17:00-00:00", thursday: "17:00-00:00", friday: "17:00-00:00", saturday: "17:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/komapo",
      gPlaceId: ""
    },
    {
      name: "Konoba Adio Mare",
      address: "Ulica Marka Pola 2",
      city: "Korčula",
      category: "Restoran",
      tags: "Restoran morske hrane,Restoran s jelima s roštilja,Taverna",
      hours: { sunday: "07:00-23:00", monday: "07:00-23:00", tuesday: "07:00-23:00", wednesday: "07:00-23:00", thursday: "07:00-23:00", friday: "07:00-23:00", saturday: "07:00-23:00" },
      maxCapacity: 50,
      description: "Tavern where they stood three generationsDear guests, welcome to the family tavern, which in 1974 founded our grandpa Cvijo. The dishes you will taste are prepared with lot of love, effort and experience. Our cooks and female cooks pray for your patience while you wait for your food as it is prepared with fresh Korčula ingredients and is cooked on the barbecue. By doing so it takes a little more time than in other restaurants, but we will do our best that you feel good in our tavern.The first section is the central part of the tavern dominated by the kitchen around which there are six tables. In the second section there are two large tables suitable for 14 guests each, and they are placed in the beautiful setting of an old shipbuilding w",
      bookingLink: "https://bookyour.smokvina.hr/r/adiomare",
      gPlaceId: ""
    },
    {
      name: "Sushi bar Amfora",
      address: "Mornarska 24",
      city: "Trogir",
      category: "Restoran",
      tags: "sushi,bar,restoran",
      hours: { sunday: "12:00-23:00", monday: "12:00-23:00", tuesday: "12:00-23:00", wednesday: "12:00-23:00", thursday: "12:00-23:00", friday: "12:00-23:00", saturday: "12:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/bvm",
      gPlaceId: ""
    },
    {
      name: "Bistro Dalmatino Luka Kneže",
      address: "Luka Kneža bb",
      city: "Račišće",
      category: "Restoran",
      tags: "Restoran morske hrane,Restoran s jelima s roštilja,Restoran za doručke",
      hours: { sunday: "09:00-23:00", monday: "09:00-23:00", tuesday: "09:00-23:00", wednesday: "09:00-23:00", thursday: "09:00-23:00", friday: "09:00-23:00", saturday: "09:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/bdlk",
      gPlaceId: ""
    },
    {
      name: "Alkarski Dvori",
      address: "Put Petrovca 12",
      city: "Sinj",
      category: "Restoran",
      tags: "",
      hours: { sunday: "07:00-23:00", monday: "07:00-23:00", tuesday: "07:00-23:00", wednesday: "07:00-23:00", thursday: "07:00-23:00", friday: "00:00-00:00", saturday: "07:00-23:00" },
      maxCapacity: 500,
      description: "<p>Restoran Alkarski Dvori u srcu je Cetinskog kraja , tako da je u našoj cjelokupnoj ponudi&nbsp; veliki izbor domaćih autohtonih i tradicionalnih jela.&nbsp;<br />\nSinj i cetinski kraj su pravi raj za gurmane, prepoznatljiv po vrlo ukusnim i jedinstvenim jelima i tu činjenicu upravo upotpunjuje naš restoran koji se&nbsp;nalazi u sklopu povijesnih i velebnih Alkarskih dvora.<br />\n&nbsp;<br />\nUgodan, ali sofisticiran ambijent pruža savršenu pozadinu za intimne večere, posebne proslave i nezaboravna okupljanja. Bilo da uživate u romantičnoj večeri za dvoje ili ste domaćin veselog događaja.</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/alkarskidvori",
      gPlaceId: ""
    },
    {
      name: "Ranch Mustang",
      address: "Glavice 199A",
      city: "Sinj",
      category: "Restoran",
      tags: "Izletište, Park sa životinjama, Jahalište",
      hours: { sunday: "10:00-20:00", monday: "10:00-20:00", tuesday: "10:00-20:00", wednesday: "10:00-20:00", thursday: "10:00-20:00", friday: "10:00-20:00", saturday: "10:00-20:00" },
      maxCapacity: 200,
      description: "<h3>Nalazimo se u Glavicama 2 kilometra od Sinja, Obiteljsko izletište obuhvaća 20 000 četvornih metara zelene površine koja uključuje koral za konje, pašnjak, livadu, sportski teren, zog za balote, trim stazu i restoran.</h3>\n\n<p>Daleko od gradske gužve u oazi mira i tišine, ugosititi ćemo Vas u našem restoranu gdje njegujemo domaću hranu i vina uz prekrasnu atmosferu.Za Vas idealan odmor tu su i naši apartmani sa jakuziem i ugodnim sobama, koji će zadovoljiti svakog.Za cijene i dostupnost molimo kontaktirajte nas.</p>\n\n<p><br />\n<em>&Scaron;to možete očekivati:</em><br />\n&bull; Mirni, zdravi i &scaron;kolovani konji individualno se prilagođavaju svakoj osobi.<br />\n&bull; Odlazak na rijeku Cetinu i jezero Peruća.<br />\n&bull; Potpuno opremljeni apartmani, uz kori&scaron;tenje jakuzija i vrtova.<br />\n&bull; Daleko od gradske buke.<br />\n&bull; Nezaboravan odmor uz konkurentne cijene.<br />\n&bull; &Scaron;kola jahanja.<br />\n&bull; Izleti za djecu i umirovljenike.<br />\n&bull; Team building, te razne sportske aktivnosti<br />\n&bull; Domaćinstvo koje njeguje domaću hranu i vino i prekrasna atmosfera</p>\n\n<p>Naši Konji</p>\n\n<p>Svi konji su izrazito mirni i &scaron;kolovani te ih se može bez ikakvih problema jahati. .. Naši konji su odmor</p>\n\n<h3>Klub Mustang ima 15 konja i djeluje dugi niz godina.</h3>\n\n<p>&nbsp;Osim &scaron;kole jahanja za djecu i odrasle organizira izlete u prirodi za vrtiće i &scaron;kole te jahanje i druženje sa konjima.</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/ranchmustang",
      gPlaceId: ""
    },
    {
      name: "OPG ZLATOVIŠĆE",
      address: "Vinogradci 5, Radovčići",
      city: "GRUDA",
      category: "WINE TASTING CELLAR",
      tags: "",
      hours: { sunday: "10:00-20:00", monday: "10:00-20:00", tuesday: "10:00-20:00", wednesday: "10:00-20:00", thursday: "10:00-20:00", friday: "10:00-20:00", saturday: "10:00-20:00" },
      maxCapacity: 60,
      description: "<h2><strong>ZLATOVI&Scaron;E&nbsp;Tavern - Wine tasting</strong></h2>\n\n<p>Wine tasting in the traditional rustically details ambient with sounds of dalmatian music which make you can feel the way how our ancients were enjoying are the perfect place for having a good time.</p>\n\n<p>We organise groups excursions up to 50 peoples, where we offer traditional menu for lunch or dinner with live music according your request.</p>\n\n<h3><strong>Accommodation</strong></h3>\n\n<p>Relax during resting in our traditional stone house at property Zlatovisce and let the time just passing by enjoying...</p>\n\n<h3><strong>Tavern</strong></h3>\n\n<p>Let the wine tasting tavern be Your choice for having good time in traditional rustically ambient...</p>\n\n<h3><strong>Our&nbsp;Products</strong></h3>\n\n<p>Taste or buy our home made products prepared on base of special ancient family receipts...</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/zlatovisce",
      gPlaceId: ""
    },
    {
      name: "BISTRO MZ",
      address: "Antuna Augustinčića 8",
      city: "ZAGREB",
      category: "Restoran",
      tags: "",
      hours: { sunday: "08:00-17:00", monday: "08:00-23:00", tuesday: "08:00-23:00", wednesday: "08:00-23:00", thursday: "08:00-23:00", friday: "08:00-23:00", saturday: "08:00-23:00" },
      maxCapacity: 90,
      description: "<h2>Obiteljska tradicija</h2>\n\n<p>Bistro MZ nalazi se u zagrebačkom kvartu Ravnice. &ldquo;Kod Srbina&rdquo; &ndash; ime je pod kojim nas prepoznaju Zagrepčani, kao i gosti grada Zagreba.</p>\n\n<p>Naša obiteljska priča traje jo&scaron; od davne 1983. godine, kada otac Milan otvara svoju prvu pečenjaru u Zagrebu. Ubrzo nakon otvaranja, kao &scaron;ef kuhinje, pridružuje mu se Voja Miličević. Okus autohtonih jela domaće srpske kuhinje i istočnjačke gastro okuse Voja je uspje&scaron;no prenio u na&scaron;e dvori&scaron;te. Njegovo kulinarsko umijeće koje je orijentirano na nacionalnu kuhinju i specijalitete vrhunsko je zahvaljujući i odrastanju uz oca vrsnog kuhara u Kru&scaron;evcu. Mućkalica, vje&scaron;alica, gurmanska pljeskavica, ćevapi, specijalitet kuće Ruža Hrvatska&hellip; jela su s ro&scaron;tilja po kojima smo prepoznatljivi i nadaleko poznati.</p>\n\n<p>Bistro MZ otvoren je 2002. godine te pod palicom mlađih nara&scaron;taja obitelji Labus uspje&scaron;no nastavlja tradiciju. Najpoznatiji smo po specijalitetima srpske nacionalne kuhinje te obilatim i kvalitetnim gablecima &ndash; &scaron;pek fileki, grah s rebricama, sarma, bakalar&hellip; po prihvatljivim cijenama uz svakodnevnu promjenu menija.</p>\n\n<p>Prostor bistroa MZ odi&scaron;e domaćom atmosferom, prostor je klimatiziran te ima terasu i osigurano parkirali&scaron;te.</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/bistromz",
      gPlaceId: ""
    },
    {
      name: "Gurme Tapas & Wine",
      address: "Marije Maričić 9",
      city: "Hvar",
      category: "Restaurant",
      tags: "Tapas & Wine",
      hours: { sunday: "16:00-00:00", monday: "16:00-00:00", tuesday: "16:00-00:00", wednesday: "16:00-00:00", thursday: "16:00-00:00", friday: "16:00-00:00", saturday: "16:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/gurmehvar",
      gPlaceId: ""
    },
    {
      name: "Konoba Kala Supetar",
      address: "Kala 7",
      city: "Supetar",
      category: "Restaurant",
      tags: "Konoba",
      hours: { sunday: "12:00-15:00 18:00-23:00", monday: "18:00-23:00", tuesday: "12:00-15:00 18:00-23:00", wednesday: "12:00-15:00 18:00-23:00", thursday: "12:00-15:00 18:00-23:00", friday: "12:00-15:00 18:00-23:00", saturday: "12:00-15:00 18:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/kalasupetar",
      gPlaceId: ""
    },
    {
      name: "Restoran Skrivena Dalmacija",
      address: "Svetog Nikole Tavelić 1",
      city: "Dugopolje",
      category: "Restaurant",
      tags: "",
      hours: { sunday: "08:00-22:00", monday: "08:00-22:00", tuesday: "08:00-22:00", wednesday: "08:00-22:00", thursday: "08:00-22:00", friday: "08:00-22:00", saturday: "08:00-22:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "",
      gPlaceId: ""
    },
    {
      name: "Rocco O.U.",
      address: "Riva 31",
      city: "Stari Grad",
      category: "Pizzeria",
      tags: "Mesni restoran,Restoran s jelima s roštilja,Restoran s mesnim jelima",
      hours: { sunday: "10:30-01:00", monday: "10:30-01:00", tuesday: "10:30-01:00", wednesday: "10:30-01:00", thursday: "10:30-01:00", friday: "10:30-01:00", saturday: "10:30-01:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/roccohvar",
      gPlaceId: ""
    },
    {
      name: "Prijevoznički obrt Boban",
      address: "A.Starčevića 185",
      city: "Solin",
      category: "Autobus prijevoznik",
      tags: "",
      hours: { sunday: "00:00-23:00", monday: "00:00-23:00", tuesday: "00:00-23:00", wednesday: "00:00-23:00", thursday: "00:00-23:00", friday: "00:00-23:00", saturday: "00:00-23:00" },
      maxCapacity: 200,
      description: "",
      bookingLink: "",
      gPlaceId: ""
    },
    {
      name: "Magazinska Klet",
      address: "Magazinska ulica 7",
      city: "Zagreb",
      category: "Restoran",
      tags: "Mesni restoran",
      hours: { sunday: "12:00-20:00", monday: "09:00-23:00", tuesday: "09:00-23:00", wednesday: "09:00-23:00", thursday: "09:00-23:00", friday: "09:00-23:00", saturday: "11:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://magazinska-klet.hr/",
      gPlaceId: ""
    },
    {
      name: "OPG Izletište Lučić",
      address: "Nart 10/A",
      city: "Gornji Dolac",
      category: "Restoran i Izletište",
      tags: "",
      hours: { sunday: "09:00-20:00", monday: "09:00-20:00", tuesday: "09:00-20:00", wednesday: "09:00-20:00", thursday: "09:00-20:00", friday: "09:00-20:00", saturday: "09:00-20:00" },
      maxCapacity: 50,
      description: "<h1>&Scaron;to možete vidjeti</h1>\n\n<p>Za svakoga pone&scaron;to</p>\n\n<p><img alt=\"\"Food icon\"\" src=\"\"https://izletistelucic.com/assets/img/icons/food.svg\"\" /></p>\n\n<h3>Hrana kakvu želi&scaron;</h3>\n\n<p>Zasigurno domaća jela kakvu su jeli na&scaron;i stari, gdje su nepca puna okusa nezaboravne tradicijske hrane od soparnika, ra&scaron;tike, peke pa do nezaobilazne janjetine s ražnja. Sve od prirode bez aditiva i bilo kakvih umjetnih okusa. Ku&scaron;anje na&scaron;e hrane je jedinstveno, prirodno i nadasve zdravo.</p>\n\n<p><img alt=\"\"Party icon\"\" src=\"\"https://izletistelucic.com/assets/img/icons/party.svg\"\" /></p>\n\n<h3>Zabavan izlet za sve uzraste</h3>\n\n<p>Daleko od gradske vreve, užurbanih života i jurećih automobila osjetite mir i život u prirodi i s prirodom. Za djecu preskanje bala sijena i druženje sa životinjama a odrasli mogu baciti na balote ili &scaron;ijavice ukoliko znaju, a ukoliko ne znaju tu smo da ih podučimo.</p>\n\n<p><img alt=\"\"Animals icon\"\" src=\"\"https://izletistelucic.com/assets/img/icons/animals.svg\"\" /></p>\n\n<h3>Veliki broj životinja</h3>\n\n<p>U na&scaron;oj ponudi imamo raznovrsni zoolo&scaron;ki vrt s egzotičnim i domaćim životinja, na&scaron; mini ZOO sadržava preko 30 različitih vrsta životinja. Također nudimo satove jahanja za vas koji želite probati ne&scaron;to novo ili vas koji želite pokazati iskustvo u jahanju.</p>\n\n<p><img alt=\"\"Tree icon\"\" src=\"\"https://izletistelucic.com/assets/img/icons/tree.svg\"\" /></p>\n\n<h3>Netaknuta priroda</h3>\n\n<p>Na&scaron;e imanje je na mosorskoj idili koju okružuje &scaron;uma daleko od gradskog asfalta. Pravo mjesto za doći i osjetiti dodir s prekrasnom prirodom koju pruža ovaj mosorski zaseok.</p>\n\n<p><img alt=\"\"Relax icon\"\" src=\"\"https://izletistelucic.com/assets/img/icons/relax.svg\"\" /></p>\n\n<h3>Savr&scaron;en odmor</h3>\n\n<p>Uvjerljivo savr&scaron;eno mjesto za odmor i opu&scaron;tanje uz prirodu, životinje, vrhunsku domaću hranu te upoznavanje tradicije. Neprocijenjivo iskustvo na dlanu svega 30min od Splita i Omi&scaron;a.</p>\n\n<p><img alt=\"\"Dance icon\"\" src=\"\"https://izletistelucic.com/assets/img/icons/dance.svg\"\" /></p>\n\n<h3>Upoznat ćete na&scaron;u tradiciju</h3>\n\n<p>Upoznajte na&scaron;u dugogodi&scaron;nju tradiciju koja datira jo&scaron; iz 13. stoljeća za vrijeme Poljičke Republike. Možete vidjeti staru arhitekturu i upoznati se s običajima te na trenutak osjetiti čar onda&scaron;njeg načina života.</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/izletistelucic",
      gPlaceId: ""
    },
    {
      name: "Konoba Koraceva kuca",
      address: "Koraceva ulica bb",
      city: "Gruda",
      category: "Restoran",
      tags: "Prodavaonica električnih motora,Servis za obnavljanje motora,Servis za popravak malih motora",
      hours: { sunday: "", monday: "08:00-16:00", tuesday: "08:00-16:00", wednesday: "08:00-16:00", thursday: "08:00-16:00", friday: "08:00-16:00", saturday: "" },
      maxCapacity: 50,
      description: "Ovlašteni zastupnici KARCHER i Kubota motora i prodaja originalnih rezervnih dijelova.Tvrtka Remontni centar Eraković je osnovana 2016. god i od samih početaka se trudila i radi po tom principu, da jedini kriterij njenog poslovanja budu zadovoljna lica krajnjih korisnika.Shodno tome i uz prethodno iskustvo njenih zaposlenih u struci, konstantno se radi na usavršavanju i specijalizacijama njenih zaposlenih kao i spremnosti za izlazak u susret prema krajnjim korisnicima, bilo informacijom tehničke prirode, cjenovne ili nekakve treće opcije. Na bilo koju vrstu popravka koja se obavi od strane naših zaposlenih, dobija se određeni vid garancije, u ovisnosti od tipa motora, vozila ili stroja, po čemu smo apsolutno jedinstveni u čitavoj regije.",
      bookingLink: "https://smokvina.hr/bookyour/r/rce",
      gPlaceId: ""
    },
    {
      name: "Božićno selo Gornji Dolac",
      address: "Nart 10/A",
      city: "Gornji Dolac",
      category: "Izletište",
      tags: "Park sa životinjama, Božićno selo",
      hours: { sunday: "", monday: "16:00-22:00", tuesday: "16:00-22:00", wednesday: "16:00-22:00", thursday: "16:00-22:00", friday: "16:00-22:00", saturday: "" },
      maxCapacity: 50,
      description: "<h1>Božićno Selo</h1>\n\n<h3>Gornji Dolac</h3>\n\n<p>Otvorenje 2.12. u 17h<br />\n<br />\n&Scaron;to možete očekivati?<br />\nKreirane stazice za najljep&scaron;e poglede sa Mosora.<br />\nScene u kojima će&scaron; napraviti stotine best-ever fotografija. Ambijent o kojem će tvoja ekipa jo&scaron; dugo pričati<br />\nPomoć i susretljivost na&scaron;ih zaposlenika.<br />\n<br />\nNe brini ni za hranu i piće, mi smo spremni vi slobodno dođite gladni...</p>\n\n<p>Veselimo se va&scaron;em dolasku!</p>\n\n<h1>&Scaron;to nudimo?</h1>\n\n<h1>Hrana</h1>\n\n<h1>Životinje</h1>\n\n<h1>Milijune Lampica</h1>\n\n<h1>Djed Božićnjak</h1>\n\n<h1>Atomsfera</h1>\n\n<h1>Zabava za sve uzraste</h1>\n\n<p>O nama</p>\n\n<p>Kako je sve počelo?</p>\n\n<p>U Dolcu Gornjem, ali ne onom &scaron;to odmah vuče na poznatiji Primorski, nego onom istočnijem, put Omi&scaron;a, podno sjeverne strane Mosora, kada zapu&scaron;e bura, hladno je, rekli bi na selu, ka u jaceri. Mrznu ruke, mrznu noge, ledeno je i kada se po &scaron;kolski slojevito obuče&scaron;. Kraj je to tipični dalmatinski brdski, s vi&scaron;etonskim gromadama od stina, s putevima u brdo koji vode negdje, nigdje. Oni &scaron;to su se kroz godine u kojima se trbuhom za kruhom, i privučen svjetlima grada polako iseljavao ljudski život, gubili pod slojevima &scaron;iblja, grmlja, odrona. I gle čuda, u toj pustopoljini, u malom zbiru napu&scaron;tenih starih kamenih djedovina, u seocetu bez tekuće vode, kanalizacije, noćne rasvjete, Tihomir Lučić, 38-godi&scaron;nji vizionar, odlučio je stvoriti Božićno selo.</p>\n\n<p>Naumio je čovjek ovdje Bogu iza leđa dovesti Božić rasko&scaron;an kao nigdje u Dalmaciji, onaj zbog kojih će se iz Splita, &Scaron;ibenika, Dubrovnika potezati put Trnbusa. Pa onda jo&scaron; malo gore, dolje, okolo do Dolca Gornjeg. I on to stvarno zaozbiljno misli. Zapravo on misli ovo: Ovdje, točno tu na ovim ledinama za prvu sljedeću adventsku nedjelju, e ovu prvu iz aktualne 2018. godine, imat ćemo Božićno selo. I to ono s milijun lampica. Točno tako. I to je to, nemam tu &scaron;ta dodat ni oduzet. Tako san odlučija, a kad ja ne&scaron;to odlučin, onda povratka nema. A &scaron;ta je luđe, ja uporniji. Ja se držim rečenice &ndash; Tko u čuda viruje, taj čuda i stvara. Zato nema odustajanja &ndash; kaže nam Tihomir skroz ozbiljno da ozbiljniji biti ne može.</p>\n\n<p>Kako najluđe stvari na ovom svijetu na pamet padaju u nekim najčudnijim trenucima, tako se ideja o milijun svića Tihomiru dogodila u trenucima kada je trpio milijun muka. Uhvatila su ga leđa, svitlilo mu je, kaže, pred očima, i dok se noću borio s bolovima, dosjetio se novog projekta. Kaže da je Božićno selo u toj svoj rasko&scaron;i ugledao upravo u tom trenutku, s tom mi&scaron;lju zaspao, s njom se probudio i potom je izložio ostatku obitelji.</p>\n\n<h1>Česta pitanja</h1>\n\n<p><strong>Je li moguć pristup osobama s invaliditetom?</strong></p>\n\n<p>Moguć je pristup osobama s invaliditetom.</p>\n\n<p><strong>Radite li nedjeljom i praznicima?</strong></p>\n\n<p>Manifestacija je otvorena svakog dana, osim badnjeg dana i stare godine kada smo zatvoreni.</p>\n\n<p><strong>Koji dan je najbolji za posjet</strong></p>\n\n<p>Predlažemo radne dane u tjednu zbog manje gužve.</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/bozicnoselo",
      gPlaceId: ""
    },
    {
      name: "Restaurant Dubrovnik",
      address: "Marojice Kaboge 5",
      city: "Dubrovnik",
      category: "Restoran",
      tags: "",
      hours: { sunday: "12:00-00:00", monday: "12:00-00:00", tuesday: "12:00-00:00", wednesday: "12:00-00:00", thursday: "12:00-00:00", friday: "12:00-00:00", saturday: "12:00-00:00" },
      maxCapacity: 200,
      description: "<p><strong>RESTAURANT DUBROVNIK&nbsp;IS CONSTANTLY PROVING ITS REPUTATION</strong><br />\nas being amongst Dubrovnik&rsquo;s top class restaurants, serving a consistently good quality food with a distinctly modern Dalmatian twist.</p>\n\n<p><strong>SITUATED LITERALLY&nbsp;MINUTES FROM&nbsp;THE MAIN STREET&nbsp;STRADUN</strong><br />\nand just a stone throw from the popular Green market, featuring the most recognizable terrace in the Old Town, this delightful place is set in one of those secluded corners of the town&rsquo;s enchanting little streets, providing the guests with just an ideal level of privacy whilst still keeping the feeling of belonging to the old urban centre. Together with exquisite service, its elegance and inspiring ambience encourages return visits since it has been reopened in 2006.</p>\n\nThe variety of their menu is fully supported by a wine list out of wich a must have is definitely White fish baked in sea salt, famous Mediterranean speciality served with cabbage and potatoes.</p>\n\n<p><strong>CATERING</strong><br />\nIntuitive service, always ready and top quality at Dubrovnik prime locations &ndash; this is the short description of our catering services. We respect your desire for different, personalized experiences.We love it! Every step you take in the city of Dubrovnik reveals cozy and beautiful places with a stunning view. We are ready to provide our ultimate catering service for all those unique places. And for all your special occasions &ndash; private or corporate events, intimate dining, luxury meals or cocktail receptions at most magical places in Dubrovnik. Because magic has no boundaries.</p>",
      bookingLink: "https://smokvina.hr/bookyour/t/dubrovnik",
      gPlaceId: ""
    },
    {
      name: "Teak Food, Wine & Cocktails",
      address: "Majstora Jurja 11",
      city: "Split",
      category: "Food, Wine & Cocktails Bar",
      tags: "",
      hours: { sunday: "08:00-00:00", monday: "08:00-00:00", tuesday: "08:00-00:00", wednesday: "08:00-00:00", thursday: "08:00-00:00", friday: "08:00-00:00", saturday: "08:00-00:00" },
      maxCapacity: 50,
      description: "<p>Teak Caffe and Cocktail Bar in Split is a vibrant and stylish establishment that offers a unique fusion of coffee and cocktails in a relaxed and welcoming atmosphere. Located in the heart of Split, our bar is known for its exceptional service and attention to detail. Whether you're looking for a perfect cup of coffee to start your day or a refreshing handcrafted cocktail to unwind in the evening, Teak Caffe and Cocktail Bar has you covered. Our skilled baristas and mixologists take pride in creating exceptional beverages using high-quality ingredients and innovative techniques. Join us at Teak Caffe and Cocktail Bar for an unforgettable experience where coffee and cocktails blend seamlessly.</p>\n\n<p>NEW from Season 2024 - breakfast, hamburgers and grill!!!</p>",
      bookingLink: "",
      gPlaceId: ""
    },
    {
      name: "Vintage Bar Hvar (Food & Cocktail Bar)",
      address: "Obala fabrika 4a",
      city: "Hvar",
      category: "Food & Cocktail Bar",
      tags: "Restaurant, Night bar",
      hours: { sunday: "18:00-02:00", monday: "18:00-02:00", tuesday: "18:00-02:00", wednesday: "18:00-02:00", thursday: "18:00-02:00", friday: "18:00-02:00", saturday: "18:00-02:00" },
      maxCapacity: 70,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/vintage",
      gPlaceId: ""
    },
    {
      name: "Hotel Restoran Mirni Kutak Otočac",
      address: "Gornja Dubrava 63",
      city: "Otočac",
      category: "Hotel",
      tags: "Restoran",
      hours: { sunday: "00:00-00:00", monday: "00:00-00:00", tuesday: "00:00-00:00", wednesday: "00:00-00:00", thursday: "00:00-00:00", friday: "00:00-00:00", saturday: "00:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/mkotocac",
      gPlaceId: ""
    },
    {
      name: "Restoran 4 Palme",
      address: "Riva 9",
      city: "Hvar",
      category: "Restoran",
      tags: "",
      hours: { sunday: "10:00-00:00", monday: "10:00-00:00", tuesday: "10:00-00:00", wednesday: "10:00-00:00", thursday: "10:00-00:00", friday: "10:00-00:00", saturday: "10:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/4palmehvar",
      gPlaceId: ""
    },
    {
      name: "Restoran Above 5 Rooftop",
      address: "Od Sigurate 4",
      city: "Dubrovnik",
      category: "Restoran",
      tags: "",
      hours: { sunday: "07:00-00:00", monday: "07:00-00:00", tuesday: "07:00-00:00", wednesday: "07:00-00:00", thursday: "07:00-00:00", friday: "07:00-00:00", saturday: "07:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/above5",
      gPlaceId: ""
    },
    {
      name: "Restoran Agava",
      address: "Ulica Ivana Božitkovića 17",
      city: "Hvar",
      category: "Restoran",
      tags: "",
      hours: { sunday: "18:30-23:00", monday: "18:30-23:00", tuesday: "18:30-23:00", wednesday: "18:30-23:00", thursday: "18:30-23:00", friday: "18:30-23:00", saturday: "18:30-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/agavahvar",
      gPlaceId: ""
    },
    {
      name: "Restoran Alavia",
      address: "Vordišće 1",
      city: "Velo Grablje",
      category: "Restoran",
      tags: "",
      hours: { sunday: "08:00-22:00", monday: "/", tuesday: "08:00-22:00", wednesday: "08:00-22:00", thursday: "08:00-22:00", friday: "08:00-22:00", saturday: "08:00-22:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/alavia",
      gPlaceId: ""
    },
    {
      name: "Aloha Bar Hvar",
      address: "Fabrika 15",
      city: "Hvar",
      category: "Bar",
      tags: "Restoran",
      hours: { sunday: "10:00-02:00", monday: "10:00-02:00", tuesday: "10:00-02:00", wednesday: "10:00-02:00", thursday: "10:00-02:00", friday: "10:00-02:00", saturday: "10:00-02:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/alohahvar",
      gPlaceId: ""
    },
    {
      name: "Luggage Storage Split",
      address: "Ulica Kralja Zvonimira 5",
      city: "Split",
      category: "Lugagge Storage Split",
      tags: "",
      hours: { sunday: "08:00-15:00", monday: "08:00-15:00", tuesday: "08:00-15:00", wednesday: "08:00-15:00", thursday: "08:00-15:00", friday: "08:00-15:00", saturday: "08:00-13:00" },
      maxCapacity: 100,
      description: "<p>Welcome to our convenient and <strong>secure luggage storage</strong> facility located in the<strong> heart of Split, Croatia</strong>. If you find yourself with some free time before your departure and are unsure where to safely store your bags, look no further.<br />\nOur dedicated team is ready to assist you with storing your personal belongings in our well-maintained and spacious office. We understand the importance of providing a reliable storage solution for travelers like yourself, ensuring that your bags are secure while you explore the beautiful city of Split.</p>\n\n<p>Our luggage storage service is <strong>available in-store from 08:00 to 20:00,</strong> allowing you to conveniently drop off and collect your items at a time that suits your travel schedule. Whether you're catching a flight or hopping on a bus, we've got you covered.</p>\n\n<p>For the affordable <strong>price of 5 euros per bag</strong>, you can enjoy peace of mind knowing that your belongings are being kept in a safe and monitored environment. Our facility is equipped with modern security systems to ensure the utmost protection for your personal items during their stay with us.</p>\n\n<p><strong>We are open every day,</strong> making it easy for you to access your stored belongings whenever you need them. Our friendly staff is available to answer any questions you may have and provide you with exceptional service throughout your visit.</p>\n\n<p>Take advantage of our reliable luggage storage service in Split, Croatia, and <strong>enjoy your time exploring the city without the burden of carrying around your bags</strong>. Trust us to keep your personal belongings safe until you're ready to continue your journey.</p>\n\n<p><strong>We offer a variety of services, including:</strong></p>\n\n<p><strong>Luggage storage</strong></p>\n\n<p><strong>Airport transfers</strong></p>\n\n<p><strong>Land and boat tours</strong></p>\n\n<p><strong>Accommodation</strong></p>\n\n<p><strong>Booking Restaurants </strong>and more! We are committed to providing our clients with the best possible service, and we are always happy to go the extra mile. If you have any questions or requests, please do not hesitate to contact us. We would be delighted to help you plan your itinerary and book your activities. We also offer a <strong>special discount on airport transfers and tours to our luggage storage clients</strong>. To book your airport transfer or tour, simply visit our website or give us a call. We look forward to helping you have a wonderful time in Split! Sincerely,</p>\n\n<p><strong>P.S. Here are some of our most popular tours:</strong></p>\n\n<p><strong>Plitvice Lakes National Park Tour</strong></p>\n\n<p><strong>Krka National Park Tour</strong></p>\n\n<p><strong>Split Walking Tour</strong></p>\n\n<p><strong>Game of Thrones Tour</strong></p>\n\n<p><strong>Blue Cave and Hvar Island Tour</strong></p>\n\n<p><strong>We also offer a variety of custom tours, so please let us know if you have something specific in mind.</strong></p>",
      bookingLink: "https://smokvina.hr/bookyour/o/lugagge",
      gPlaceId: ""
    },
    {
      name: "Restaurant eVala 1903",
      address: "Trumbićeva obala 12, 21000, Split",
      city: "Split",
      category: "Restaurant",
      tags: "",
      hours: { sunday: "09:00-00:00", monday: "09:00-00:00", tuesday: "09:00-00:00", wednesday: "09:00-00:00", thursday: "09:00-00:00", friday: "09:00-00:00", saturday: "09:00-00:00" },
      maxCapacity: 50,
      description: "<p>Restaurant eVala 1903 offers the flavors of traditional Croatian cuisine with a modern twist, under the leadership of Chef Ivan Temšić. Located on the historic Matejuška, we draw inspiration from the local heritage of Split. Our beautiful location reflects the rich history of Tezje, and the year 1903 in the name of the restaurant commemorates the marriage of the famous Roko and Cicibela, who got married not far from our position.</p>\n\n<p>The name of our restaurant &quot;eVala 1903&quot; is a combination of several important things. The word &quot;evala&quot; itself is an old Split word meaning &quot;good luck, thank you, good day&quot;, while &quot;Vala&quot; means a sea bay.</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/evala",
      gPlaceId: ""
    },
    {
      name: "U Šime",
      address: "Zrmanjska 1",
      city: "Biograd",
      category: "Restaurant",
      tags: "",
      hours: { sunday: "08:00-16:00", monday: "08:00-23:00", tuesday: "08:00-16:00", wednesday: "08:00-16:00", thursday: "08:00-16:00", friday: "08:00-16:00", saturday: "08:00-16:00" },
      maxCapacity: 100,
      description: "<p>Family run restaurant in quiet location, concentrated on traditional dalmatian cuisine prepared on wood fire. House specialities are lamb on grill, lamb under &quot;peka&quot; and cooked lamb in traditional &quot;kotlić&quot; on wood fire.</p>\n\n<h1><strong>ONLY GROUPS AND EVENT RESERVATIONS</strong></h1>",
      bookingLink: "https://smokvina.hr/bookyour/r/usime",
      gPlaceId: ""
    },
    {
      name: "Pensatore Kitchen & Wine",
      address: "Šetalište Petra Kanavelića",
      city: "Korčula",
      category: "Restoran",
      tags: "Restoran s jelima s roštilja,Restoran s mesnim jelima",
      hours: { sunday: "08:00-23:00", monday: "08:00-23:00", tuesday: "08:00-23:00", wednesday: "08:00-23:00", thursday: "08:00-23:00", friday: "08:00-23:00", saturday: "08:00-23:00" },
      maxCapacity: 50,
      description: "Local restaurant situated at a premium spot on Korčula’s old town promenade with breathtaking views overlooking the panorama of Pelješac channel.",
      bookingLink: "https://smokvina.hr/bookyour/r/pensatorekor",
      gPlaceId: ""
    },
    {
      name: "Bistro pizzeria More Divulje by Split Airport",
      address: "Put Divulja 50",
      city: "Kaštel Štafilić",
      category: "restoran",
      tags: "",
      hours: { sunday: "07:00-23:00", monday: "07:00-22:00", tuesday: "07:00-22:00", wednesday: "07:00-22:00", thursday: "07:00-22:00", friday: "07:00-22:00", saturday: "07:00-22:00" },
      maxCapacity: 500,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/more",
      gPlaceId: ""
    },
    {
      name: "Farm House Library",
      address: "Vrvilo-Polić 79",
      city: "Brštanovo",
      category: "Restoran",
      tags: "",
      hours: { sunday: "08:00-00:00", monday: "08:00-00:00", tuesday: "08:00-00:00", wednesday: "08:00-00:00", thursday: "08:00-00:00", friday: "08:00-00:00", saturday: "08:00-00:00" },
      maxCapacity: 50,
      description: "<p><u><strong>CHECK MENU FOR GROUPS AND MENUS PLEASE CALL ON +38598667806</strong></u></p>\n\n<p>&nbsp;</p>\n\n<p><u><strong>FARM DINNER TRADITIONAL DALMATIAN &quot;PEKA&quot;</strong></u><br />\n<strong>WELCOME COCKTAIL&nbsp;</strong>Local cocktail and/or aperol spritz<br />\n<strong>FIRST COURSE&nbsp;</strong>Prosciutto, goat and cow cheese, &ldquo;soparnik&rdquo;, dried tomatoes, fig spread<br />\n<strong>SECOND COURSE&nbsp;</strong>Traditional &ldquo;peka&rdquo; - rooster or veal, with potatoes. Seasonal salad from the farm<br />\n<strong>DESSERT&nbsp;</strong>Homemade cake<br />\n<strong>DRINKS MENU&nbsp;</strong>White Wine, Red Wine, Sparkling, Water,<br />\n<u><strong>Price 70 &euro; per person. Minimum number of adults 10.</strong></u></p>\n\n<p>&nbsp;</p>\n\n<p><u><strong>CHARCUTERIE BOARD</strong></u><br />\n<strong>WELCOME COCKTAIL.</strong> Local cocktail or aperol spritz.<br />\nCroatian prosciutto. Local cheeses. Soparnik (traditional Croatian vegan Swiss chard dish).<br />\n<strong>DESSERT.</strong> Homemade cake.<br />\n<strong>DRINKS MENU</strong> White Wine, Red Wine, Water, Sparkling Water<br />\n<u><strong>Price &euro;55 per person. Minimum number of adults 10.</strong></u></p>\n\n<p>&nbsp;</p>\n\n<p><strong><u>TRADITIONAL DALMATIAN &quot;TUNA&quot;</u><br />\nWELCOME COCKTAIL</strong>&nbsp;Local cocktail and/or aperol spritz<br />\n<strong>FIRST COURSE</strong>&nbsp;Marinated Salted Anchovies, goat and cow cheese, &ldquo;soparnik&rdquo;, dried tomatoes, fig&nbsp;spread<br />\n<strong>SECOND COURSE&nbsp;</strong>Grilled Tuna Steak with Swiss chard and boiled potatoes.&nbsp;Seasonal salad from the farm<br />\n<strong>DESSERT</strong>&nbsp;Homemade cake<br />\n<strong>DRINKS MENU</strong>&nbsp;White Wine, Red Wine, Sparkling, Water,<br />\n<u><strong>Price 85 &euro; per person.&nbsp;Minimum number of adults 10.</strong></u></p>\n\n<p>&nbsp;</p>\n\n<p><u><strong>Vegan Pa&scaron;ticada</strong></u><br />\n<strong>WELCOME COCKTAIL&nbsp;</strong>Local cocktail and/or aperol spritz<br />\n<strong>FIRST COURSE&nbsp;</strong>&ldquo;soparnik&rdquo;, dried tomatoes, hummus,<br />\n<strong>SECOND COURSE&nbsp;</strong>Vegan Pa&scaron;ticada with Gnocchi.&nbsp;Traditional Dalmatian-style stew with seitan and mushrooms, served with gnocchi&nbsp;Seasonal salad from the farm<br />\n<strong>DESSERT</strong>&nbsp;Vegan Homemade cake<br />\n<strong>DRINKS MENU</strong>&nbsp;White Wine, Red Wine, Sparkling, Water,<br />\n<u><strong>Price 75 &euro; per person.&nbsp;Minimum number of adults 10.</strong></u></p>\n\n<p><br />\n<u><strong>Rib-Eye steak</strong></u><br />\n<strong>WELCOME COCKTAIL</strong>&nbsp;Local cocktail and/or aperol spritz<br />\n<strong>FIRST COURSE&nbsp;</strong>Prosciutto, goat and cow cheese, &ldquo;soparnik&rdquo;<br />\n<strong>SECOND COURSE</strong>&nbsp;Rump steak with potatoes.&nbsp;Seasonal salad from the farm<br />\n<strong>DESSERT</strong>&nbsp;Homemade cake<br />\n<strong>DRINKS MENU</strong><br />\nWhite Wine, Red Wine, Sparkling Water<br />\n<u><strong>Price 80 &euro; per person.&nbsp;* minimum number of adults is 10</strong></u></p>",
      bookingLink: "https://smokvina.hr/bookyour/r/farmhouse",
      gPlaceId: ""
    },
    {
      name: "Dva Ribara",
      address: "Obala Fabrike 31",
      city: "Hvar",
      category: "Bistro",
      tags: "Mesni restoran,Restoran,Restoran morske hrane,Restoran s mesnim jelima,Restoran zdrave prehrane",
      hours: { sunday: "11:30-23:30", monday: "11:30-23:30", tuesday: "11:30-23:30", wednesday: "11:30-23:30", thursday: "11:30-23:30", friday: "11:30-23:30", saturday: "11:30-23:30" },
      maxCapacity: 10,
      description: "",
      bookingLink: "https://bookyour.smokvina.hr/r/dvaribara",
      gPlaceId: ""
    },
    {
      name: "Uje Oil Bar",
      address: "Dominisova ulica 3",
      city: "Split",
      category: "Restoran",
      tags: "Wine tasting, Wine bar, Wine Club",
      hours: { sunday: "08:00-00:00", monday: "08:00-00:00", tuesday: "08:00-00:00", wednesday: "08:00-00:00", thursday: "08:00-00:00", friday: "08:00-00:00", saturday: "08:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://bookyour.smokvina.hr/r/uob",
      gPlaceId: ""
    },
    {
      name: "Restoran Villa Dinka",
      address: "Dinka Kovačevića 14",
      city: "Hvar",
      category: "Restoran",
      tags: "Dobavljač građevinske opreme,Iznajmljivanje alata,Prodavaonica drvne građe,Rasadnik božićnih drvaca,Zimska služba",
      hours: { sunday: "18:00-23:00", monday: "18:00-23:00", tuesday: "18:00-23:00", wednesday: "18:00-23:00", thursday: "18:00-23:00", friday: "18:00-23:00", saturday: "18:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/rapr",
      gPlaceId: ""
    },
    {
      name: "Faria Garden Terrace",
      address: "Dr. Mate Miličića 12",
      city: "Hvar",
      category: "Restoran",
      tags: "Restoran morske hrane,Restoran s jelima s roštilja,Restoran s mesnim jelima",
      hours: { sunday: "14:00-23:00", monday: "16:00-00:00", tuesday: "16:00-00:00", wednesday: "16:00-00:00", thursday: "16:00-00:00", friday: "16:00-00:00", saturday: "16:00-00:00" },
      maxCapacity: 50,
      description: "Welcome to our garden terrace \"FARIA\"!Our friendly staff awaits you in a homely ambience with Dalmatian specialties, at moderate prices, prepared on natural grilling.We look forward to your visit!",
      bookingLink: "https://bookyour.smokvina.hr/r/restaurantfaria",
      gPlaceId: ""
    },
    {
      name: "10 U POLA",
      address: "Put firula 57",
      city: "Split",
      category: "Grill restaurant",
      tags: "",
      hours: { sunday: "8:00 - 23:00", monday: "8:00 - 23:00", tuesday: "8:00 - 23:00", wednesday: "8:00 - 23:00", thursday: "8:00 - 23:00", friday: "8:00 - 23:00", saturday: "8:00 - 23:00" },
      maxCapacity: 100,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/10upola",
      gPlaceId: ""
    },
    {
      name: "Restoran Gusar",
      address: "Spinutska ulica 69",
      city: "Split",
      category: "Restoran",
      tags: "Jelovnik za vjenčanja,Mjesto za vjenčanja,Restoran morske hrane,Restoran s jelima s roštilja,Restoran s mesnim jelima,Restoran za rane ručke,Riblji restoran (specijaliziran za grdobinu),Usluge za vjenčanja",
      hours: { sunday: "10:00-23:00", monday: "10:00-23:00", tuesday: "10:00-23:00", wednesday: "10:00-23:00", thursday: "10:00-23:00", friday: "10:00-23:00", saturday: "10:00-23:00" },
      maxCapacity: 50,
      description: "Proslavite svoj zavjet ljubavi s Vama dragimosobama uz vrhunsku uslugu i bogatu gastronomsku ponudu u ugodnom ambijentu restorana Gusar. Bilo da planirate vjenčanje, privatnu zabavu, poslovno druženje ili neku drugu proslavu prepustite brigu oko cateringa iskusnom osoblju restorana Gusar. Ekipa vrhunskih profesionalaca udovoljit će svakoj Vašoj želji. Restoran za sve Vaše svečanosti!Dođite i osjećajte se ugodno u prekrasnom ambijentu restorana Gusar! Organiziramo krštenja, pričesti, krizme, obiteljske i privatne proslave, poslovne sastanke i seminare.",
      bookingLink: "https://smokvina.hr/bookyour/o/rgst",
      gPlaceId: ""
    },
    {
      name: "Restaurant Adriatic",
      address: "Sustipanski put 2",
      city: "Split",
      category: "Restaurant",
      tags: "",
      hours: { sunday: "12:00-01:00", monday: "12:00-01:00", tuesday: "12:00-01:00", wednesday: "12:00-01:00", thursday: "12:00-01:00", friday: "12:00-01:00", saturday: "12:00-01:00" },
      maxCapacity: 50,
      description: "<p>Deeply immersed in the colors and flavors of the Mediterranean, Restaurant Adriatic is a high quality every day food venue with breathtaking sea view!</p>",
      bookingLink: "https://smokvina.hr/bookyour/o/rbbr",
      gPlaceId: ""
    },
    {
      name: "Taverna Riva Bol",
      address: "Frane Radića 5",
      city: "Bol",
      category: "Konoba",
      tags: "Restoran",
      hours: { sunday: "11:00-00:00", monday: "11:00-00:00", tuesday: "11:00-00:00", wednesday: "11:00-00:00", thursday: "11:00-00:00", friday: "11:00-00:00", saturday: "11:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/tavernabol",
      gPlaceId: ""
    },
    {
      name: "Restaurant Palace Paladini",
      address: "Petra Hektorovica 4",
      city: "Hvar",
      category: "Restoran",
      tags: "",
      hours: { sunday: "11:00-00:00", monday: "11:00-01:00", tuesday: "11:00-01:00", wednesday: "11:00-01:00", thursday: "11:00-01:00", friday: "11:00-01:00", saturday: "11:00-01:00" },
      maxCapacity: 50,
      description: "Restaurant Palace Paladini is placed at the old ancient part of City of Hvar. We offer fish delicious, meat and vege specialities, greatest wines and champagnes (Dom Perignon/Rose, Crystal, Moet & Chandon...).The palace where you are about to eat belonged to an old noble family from the Hvar called Paladinic (Paladinis - Italian version; de Paladinis - Latin version).Palace de Paladinis, built in renaissance style, is one of the most beautifull and outstanding Hvar palaces, situated in the southern part of the oldest nucleus of the town Hvar below the fortress known as Forto Spagnuolo.",
      bookingLink: "https://smokvina.hr/bookyour/r/rpphvar",
      gPlaceId: ""
    },
    {
      name: "Restaurant Dolis",
      address: "Ul. Zrinsko Frankopanska 52",
      city: "Split",
      category: "Restoran",
      tags: "Bar",
      hours: { sunday: "10:00-00:00", monday: "/", tuesday: "10:00-00:00", wednesday: "10:00-00:00", thursday: "10:00-00:00", friday: "10:00-01:00", saturday: "10:00-01:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/dolis",
      gPlaceId: ""
    },
    {
      name: "Dos Locos No1",
      address: "Hrvatske bratske zajednice 68",
      city: "Korčula",
      category: "Koktel bar",
      tags: "Bar,Noćni klub",
      hours: { sunday: "16:00-02:00", monday: "16:00-00:00", tuesday: "16:00-02:00", wednesday: "16:00-02:00", thursday: "16:00-02:00", friday: "16:00-02:00", saturday: "16:00-02:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/b/dlno1",
      gPlaceId: ""
    },
    {
      name: "Split Boat Trips",
      address: "Obala Hrvatskog narodnog preporoda 55",
      city: "Split",
      category: "Agencija za obilaske brodom",
      tags: "",
      hours: { sunday: "00:00-00:00", monday: "00:00-00:00", tuesday: "00:00-00:00", wednesday: "00:00-00:00", thursday: "00:00-00:00", friday: "00:00-00:00", saturday: "00:00-00:00" },
      maxCapacity: 50,
      description: "<p><strong>Testing the description</strong></p>\n\n<p>This is first line</p>\n\n<p>This is second</p>\n\n<ol>\n\t<li>bull 1</li>\n\t<li>bull2</li>\n</ol>\n\n<p><em>Italic text</em></p>\n\n<ul>\n\t<li><em>bull dot 1</em></li>\n\t<li><em>bull dot2</em></li>\n</ul>\n\n<p>&nbsp;</p>",
      bookingLink: "http://split-boat-trips.com/",
      gPlaceId: ""
    },
    {
      name: "Restaurant Mediterraneo, Split",
      address: "Carrarina poljana 3",
      city: "Split",
      category: "Restoran",
      tags: "Mesni restoran,Pizzerija,Restoran s jelima s roštilja,Restoran s mesnim jelima",
      hours: { sunday: "12:00-00:00", monday: "12:00-00:00", tuesday: "12:00-00:00", wednesday: "12:00-00:00", thursday: "12:00-00:00", friday: "12:00-00:00", saturday: "12:00-00:00" },
      maxCapacity: 50,
      description: "<p>We use authentic, locally sourced ingredients to create both modern and classic style dishes from across the Mediterranean, combined with a wide range of quality wines to compliment your meal.</p>",
      bookingLink: "https://bookyour.smokvina.hr/b/rmst",
      gPlaceId: ""
    },
    {
      name: "Konoba Pizzeria Porat",
      address: "Kalebovo 2",
      city: "Vinišće",
      category: "Pizzeria",
      tags: "Restaurant, Konoba",
      hours: { sunday: "09:00-00:00", monday: "09:00-00:00", tuesday: "09:00-00:00", wednesday: "09:00-00:00", thursday: "09:00-00:00", friday: "09:00-00:00", saturday: "09:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/poratvinisce",
      gPlaceId: ""
    },
    {
      name: "Konoba Nevera",
      address: "Put Firula 17",
      city: "Split",
      category: "Restoran",
      tags: "Mediteranski restoran,Mesni restoran,Restoran morske hrane,Restoran s jelima s roštilja,Restoran s mesnim jelima,Restoran za rane ručke",
      hours: { sunday: "12:00-23:00", monday: "12:00-23:00", tuesday: "12:00-23:00", wednesday: "12:00-23:00", thursday: "12:00-23:00", friday: "12:00-23:00", saturday: "12:00-23:00" },
      maxCapacity: 50,
      description: "Nevera je ugodno prozračno mjesto van gradske vreve, tamo gdje povijesni dio Splita zamjenjuje onaj kupališni. U blizini su marine, kupališta, teniski tereni.Stara dalmatinska kuharska škola ovdje je u punoj snazi, i ako ste stvarno željni kvalitetne mediteranske hrane bez previše kerefeka, ovo je jednostavno savršeno mjesto za vas.Nevera je osvjetljenija i s više zraka od klasične konobe, po zidovima nema previše morskih detalja, ali možete uživati u maketama brodova, školjkama, bocama vina...Na repertoaru su lagane dalmatinske pjesme sa zadiranjem u rock and roll, a atmosfera ležerna, opuštena dok mirisi nježno dopiru iz kuhinje... Broj jedan na meniju ribe, sve što pliva u moru s leđima okrenutim prema nebu (stara kineska).",
      bookingLink: "https://bookyour.smokvina.hr/r/knevera",
      gPlaceId: ""
    },
    {
      name: "Dalmata fine food",
      address: "Dragoševca 10",
      city: "Vinišće",
      category: "Bistro",
      tags: "",
      hours: { sunday: "13:00-01:00", monday: "13:00-01:00", tuesday: "13:00-01:00", wednesday: "13:00-01:00", thursday: "13:00-01:00", friday: "13:00-01:00", saturday: "13:00-01:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://dalmata-fine-food.business.site",
      gPlaceId: ""
    },
    {
      name: "Konoba Bajso",
      address: "Staro selo 11",
      city: "Jesenice",
      category: "Konoba",
      tags: "Restoran",
      hours: { sunday: "12:00-22:00", monday: "/", tuesday: "/", wednesday: "/", thursday: "/", friday: "/", saturday: "12:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "http://www.bajso.com/",
      gPlaceId: ""
    },
    {
      name: "Konoba Girasole",
      address: "Ulica kralja Zvonimira 4",
      city: "Solin",
      category: "Konoba",
      tags: "Restoran, pizzeria",
      hours: { sunday: "09:00-00:00", monday: "09:00-00:00", tuesday: "09:00-00:00", wednesday: "09:00-00:00", thursday: "09:00-00:00", friday: "09:00-00:00", saturday: "09:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "",
      gPlaceId: ""
    },
    {
      name: "Paradise Garden",
      address: "Dr. Mate Miličića 8",
      city: "Hvar",
      category: "Restoran",
      tags: "Restoran morske hrane,Restoran s jelima s roštilja,Restoran s mesnim jelima",
      hours: { sunday: "12:00-01:00", monday: "12:00-01:00", tuesday: "12:00-01:00", wednesday: "12:00-01:00", thursday: "12:00-01:00", friday: "12:00-01:00", saturday: "12:00-01:00" },
      maxCapacity: 50,
      description: "A beautiful garden with a lovely staff and family with a tasty food, will give you everithing what will make you happy.",
      bookingLink: "https://bookyour.smokvina.hr/r/pghv",
      gPlaceId: ""
    },
    {
      name: "Konoba Vrilo",
      address: "Prudi ulica 193",
      city: "Metković",
      category: "Restoran",
      tags: "Mesni restoran,Restoran morske hrane,Restoran s jelima s roštilja,Restoran s mesnim jelima,Restoran s ribom i krumpirićima,Restoran zdrave prehrane",
      hours: { sunday: "10:00-23:00", monday: "10:00-23:00", tuesday: "10:00-23:00", wednesday: "10:00-23:00", thursday: "10:00-23:00", friday: "10:00-23:00", saturday: "10:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/kvrilo",
      gPlaceId: ""
    },
    {
      name: "Restaurant & Bar Dionis",
      address: "Obrov ulica 1",
      city: "Trogir",
      category: "Restoran",
      tags: "Bar,Restoran morske hrane,Restoran s mesnim jelima",
      hours: { sunday: "07:00-00:00", monday: "07:00-00:00", tuesday: "07:00-00:00", wednesday: "07:00-00:00", thursday: "07:00-00:00", friday: "07:00-00:00", saturday: "07:00-00:00" },
      maxCapacity: 50,
      description: "Located in the center of Trogir on the promenade, this nice location will make you enjoy the view and also delicious modern Mediterranean and Croatian food..Welcome!",
      bookingLink: "https://bookyour.smokvina.hr/b/rbdtg",
      gPlaceId: ""
    },
    {
      name: "Konoba Atlantida",
      address: "Trumbićeva obala 13",
      city: "Split",
      category: "Restoran",
      tags: "",
      hours: { sunday: "08:00-00:00", monday: "08:00-00:00", tuesday: "08:00-00:00", wednesday: "08:00-00:00", thursday: "08:00-00:00", friday: "08:00-00:00", saturday: "08:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/atlantida",
      gPlaceId: ""
    },
    {
      name: "Konoba-pizzeria Hila",
      address: "Mandrača 20",
      city: "Marina",
      category: "Restoran",
      tags: "Pizzerija,Restoran s jelima s roštilja,Restoran s mesnim jelima",
      hours: { sunday: "12:00-00:00", monday: "12:00-00:00", tuesday: "12:00-00:00", wednesday: "12:00-00:00", thursday: "12:00-00:00", friday: "12:00-00:00", saturday: "12:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/kph",
      gPlaceId: ""
    },
    {
      name: "Konoba Belin",
      address: "Žrnovo 50",
      city: "Korčula",
      category: "Restoran",
      tags: "Restoran morske hrane,Restoran s jelima s roštilja,Restoran s mesnim jelima,Restoran zdrave prehrane",
      hours: { sunday: "18:00-00:00", monday: "18:00-00:00", tuesday: "18:00-00:00", wednesday: "18:00-00:00", thursday: "18:00-00:00", friday: "18:00-00:00", saturday: "18:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://bookyour.smokvina.hr/b/kobko",
      gPlaceId: ""
    },
    {
      name: "Restoran Kadena",
      address: "Ulica Ivana pl. Zajca 4",
      city: "Split",
      category: "Restoran",
      tags: "",
      hours: { sunday: "08:00-22:00", monday: "08:00-22:00", tuesday: "08:00-22:00", wednesday: "08:00-22:00", thursday: "08:00-22:00", friday: "08:00-22:00", saturday: "08:00-22:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/kadena",
      gPlaceId: ""
    },
    {
      name: "Fameja",
      address: "Riva 13",
      city: "Hvar",
      category: "Restoran",
      tags: "Restoran morske hrane,Restoran s hamburgerima,Restoran s jelima s roštilja,Restoran s mesnim jelima,Restoran zdrave prehrane",
      hours: { sunday: "09:00-22:00", monday: "09:00-22:00", tuesday: "09:00-22:00", wednesday: "09:00-22:00", thursday: "09:00-22:00", friday: "09:00-22:00", saturday: "09:00-22:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/o/famejahvar",
      gPlaceId: ""
    },
    {
      name: "Hotel Adriana",
      address: "Obala Hrvatskog narodnog preporoda 8",
      city: "Split",
      category: "Hotel",
      tags: "Restoran, bar",
      hours: { sunday: "07:00-23:00", monday: "07:00-23:00", tuesday: "07:00-23:00", wednesday: "07:00-23:00", thursday: "07:00-23:00", friday: "07:00-23:00", saturday: "07:00-23:00" },
      maxCapacity: 500,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/adriana",
      gPlaceId: ""
    },
    {
      name: "Restoran Babilon",
      address: "Ulica Georgea Washingtona 13",
      city: "Split",
      category: "Restoran",
      tags: "Restoran s jelima s roštilja,Restoran s mesnim jelima",
      hours: { sunday: "09:00-00:00", monday: "09:00-00:00", tuesday: "09:00-00:00", wednesday: "09:00-00:00", thursday: "09:00-00:00", friday: "09:00-00:00", saturday: "09:00-00:00" },
      maxCapacity: 180,
      description: "<p>BABYLON RESTAURANT<br />\nLONG-TERM TRADITION AND SPECIALIZED STAFF<br />\nRestaurant Babilon is one of the oldest catering facilities in the city of Split. For years, we have been trying to meet all the challenges of modern catering, so with long-standing tradition and specialized staff, we keep up with the times. Our satisfied guests are our motivation for further success, and we hope that we have been able to meet their requirements. So come and see for yourself!</p>\n\n<p>OUR RESTAURANT IS NOW BIGGER, MORE BEAUTIFUL AND MORE MODERN</p>\n\n<p>WEDDINGS and HALL FOR 80 PEOPLE<br />\nCELEBRATION<br />\nDELIVERY AND ORGANIZATION<br />\nCATERING</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/babilonst",
      gPlaceId: ""
    },
    {
      name: "Konoba Kaleta Trogir",
      address: "Mornarska ulica 24A",
      city: "Trogir",
      category: "Restoran",
      tags: "Restoran s mesnim jelima,Restoran za doručke",
      hours: { sunday: "07:00-00:00", monday: "07:00-00:00", tuesday: "07:00-00:00", wednesday: "07:00-00:00", thursday: "07:00-00:00", friday: "07:00-00:00", saturday: "07:00-00:00" },
      maxCapacity: 500,
      description: "Elegant, comfortable atmosphere, relaxed , combined with excellent food and service. That's what makes KALETA's visitors their regular customers. Only fresh fish, meat and seafood, carefully selected vegetables and fruits - the are no trifles! Restaurant KALETA is a place where you would like to return.",
      bookingLink: "https://bookyour.smokvina.hr/b/kktg",
      gPlaceId: ""
    },
    {
      name: "Restoran Atrij Žrnovo",
      address: "Žrnovo 248",
      city: "Žrnovo",
      category: "Restoran",
      tags: "Restoran s jelima s roštilja,Restoran s mesnim jelima,Restoran zdrave prehrane",
      hours: { sunday: "18:00-23:00", monday: "18:00-23:00", tuesday: "18:00-23:00", wednesday: "18:00-23:00", thursday: "18:00-23:00", friday: "18:00-23:00", saturday: "18:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://goo.gl/forms/9SrTOcuXa9QqOg8Q2",
      gPlaceId: ""
    },
    {
      name: "Konoba Bonaca",
      address: "Riva 28",
      city: "Hvar",
      category: "Restoran",
      tags: "",
      hours: { sunday: "12:00-00:00", monday: "12:00-00:00", tuesday: "12:00-00:00", wednesday: "12:00-00:00", thursday: "12:00-00:00", friday: "12:00-00:00", saturday: "12:00-00:00" },
      maxCapacity: 50,
      description: "Our family has been in the culinary business for many years. We can proudly state that we were among the first restaurant businesses in Hvar in the 70s and during the last century. A rich palate of Mediterranean specialties and a wine chart will thrill even the most demanding gourmet. A lot of our dishes are recognized as Croatian gastronomic jewels and numerous rewards acknowledge this.",
      bookingLink: "https://smokvina.hr/bookyour/r/bonaca",
      gPlaceId: ""
    },
    {
      name: "Konoba Popret",
      address: "Put Hrvatskih branitelja 40, Gornji Brgat",
      city: "Dubrovnik",
      category: "Restoran",
      tags: "Restoran morske hrane,Restoran s jelima s roštilja,Restoran s mesnim jelima",
      hours: { sunday: "12:00-23:00", monday: "16:00-23:00", tuesday: "16:00-23:00", wednesday: "16:00-23:00", thursday: "16:00-23:00", friday: "16:00-23:00", saturday: "12:00-23:00" },
      maxCapacity: 100,
      description: "Family restaurant Konoba Popret on Brgat is property of the Nadramija family. Apart from the classic selection of dishes, Popret offers delicacies such as lamb and pork, a wide wine selection and homemade desserts. It is an ideal place for all types of celebration.",
      bookingLink: "https://smokvina.hr/bookyour/r/kpbrgat",
      gPlaceId: ""
    },
    {
      name: "Konoba Dujkin Dvor",
      address: "Trumbićeva obala 6",
      city: "Split",
      category: "Konoba",
      tags: "Restoran",
      hours: { sunday: "08:30-23:00", monday: "08:30-23:00", tuesday: "08:30-23:00", wednesday: "08:30-23:00", thursday: "08:30-23:00", friday: "08:30-23:00", saturday: "08:30-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/dujkindvor",
      gPlaceId: ""
    },
    {
      name: "Restoran Dundo Maroje",
      address: "Kovačka ulica",
      city: "Dubrovnik",
      category: "Restoran",
      tags: "",
      hours: { sunday: "10:00-23:00", monday: "10:00-23:00", tuesday: "10:00-23:00", wednesday: "10:00-23:00", thursday: "10:00-23:00", friday: "10:00-23:00", saturday: "10:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/dundomaroje",
      gPlaceId: ""
    },
    {
      name: "Eywa Bar Hvar",
      address: "Šetalište put Križa 21-A",
      city: "Hvar",
      category: "Restoran",
      tags: "Restoran, bar",
      hours: { sunday: "07:00-23:00", monday: "07:00-23:00", tuesday: "07:00-23:00", wednesday: "07:00-23:00", thursday: "07:00-23:00", friday: "07:00-23:00", saturday: "07:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/eywa",
      gPlaceId: ""
    },
    {
      name: "Falko Beach Bar",
      address: "Šetalište Tonija Petrića 22",
      city: "Hvar",
      category: "Bar",
      tags: "Restoran, bar",
      hours: { sunday: "12:00-22:00", monday: "12:00-22:00", tuesday: "12:00-22:00", wednesday: "12:00-22:00", thursday: "12:00-22:00", friday: "12:00-22:00", saturday: "12:00-22:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/falko",
      gPlaceId: ""
    },
    {
      name: "Fast Food A Je To",
      address: "Dr. Martina Žižića 11",
      city: "Solin",
      category: "Fast Food",
      tags: "",
      hours: { sunday: "/", monday: "09:00-23:00", tuesday: "09:00-23:00", wednesday: "09:00-23:00", thursday: "09:00-23:00", friday: "09:00-23:00", saturday: "09:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/ajetosolin",
      gPlaceId: ""
    },
    {
      name: "Fast Food Berekin",
      address: "Ul. kralja Zvonimira 75",
      city: "Solin",
      category: "Fast Food",
      tags: "",
      hours: { sunday: "/", monday: "08:00-23:00", tuesday: "08:00-23:00", wednesday: "08:00-23:00", thursday: "08:00-23:00", friday: "08:00-23:00", saturday: "08:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/berekin",
      gPlaceId: ""
    },
    {
      name: "Konoba Feral Brijesta",
      address: "Brijesta 18",
      city: "Janjina",
      category: "Konoba",
      tags: "Restoran",
      hours: { sunday: "12:00-18:00", monday: "12:00-18:00", tuesday: "12:00-18:00", wednesday: "12:00-18:00", thursday: "12:00-18:00", friday: "12:00-18:00", saturday: "12:00-18:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/feralbrijesta",
      gPlaceId: ""
    },
    {
      name: "Seosko Domaćinstvo Ficović",
      address: "Hodilje 30",
      city: "Ston",
      category: "Restoran",
      tags: "Restoran, bar",
      hours: { sunday: "11:00-21:00", monday: "11:00-21:00", tuesday: "11:00-21:00", wednesday: "11:00-21:00", thursday: "11:00-21:00", friday: "11:00-21:00", saturday: "11:00-21:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/ficovicston",
      gPlaceId: ""
    },
    {
      name: "Fish Restaurant Veprinova",
      address: "Gdinj 270",
      city: "Gdinj",
      category: "Restoran",
      tags: "",
      hours: { sunday: "12:00-23:00", monday: "12:00-23:00", tuesday: "12:00-23:00", wednesday: "12:00-23:00", thursday: "12:00-23:00", friday: "12:00-23:00", saturday: "12:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/veprinova",
      gPlaceId: ""
    },
    {
      name: "Brguja Omiš",
      address: "Vukovarska 7",
      city: "Omiš",
      category: "Restoran",
      tags: "Bar",
      hours: { sunday: "10:00-23:00", monday: "10:00-23:00", tuesday: "10:00-23:00", wednesday: "10:00-23:00", thursday: "10:00-23:00", friday: "10:00-23:00", saturday: "10:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/brguja",
      gPlaceId: ""
    },
    {
      name: "Chops Grill - steak&seafood",
      address: "Tončićeva ulica 4",
      city: "Split",
      category: "Restaurant",
      tags: "Restoran morske hrane,Restoran s jelima s roštilja,Restoran s mesnim jelima,Restoran za doručke",
      hours: { sunday: "12:00-23:00", monday: "12:00-23:00", tuesday: "12:00-23:00", wednesday: "12:00-23:00", thursday: "12:00-23:00", friday: "12:00-23:00", saturday: "12:00-23:00" },
      maxCapacity: 50,
      description: "<p>Chops Grill offers prime steaks, fresh seafood, and more. Watch our chefs grill to perfection in our open kitchen. Enjoy a sophisticated dining experience in the heart of Split.</p>",
      bookingLink: "https://smokvina.hr/bookyour/o/chops",
      gPlaceId: ""
    },
    {
      name: "Bistro Gajeta Korčula",
      address: "Šetalište Petra Kanavelića",
      city: "Korčula",
      category: "Restoran",
      tags: "Bistro,Restoran morske hrane,Restoran s mesnim jelima,Restoran zdrave prehrane",
      hours: { sunday: "08:00-00:00", monday: "08:00-00:00", tuesday: "08:00-00:00", wednesday: "08:00-00:00", thursday: "08:00-00:00", friday: "08:00-00:00", saturday: "08:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://goo.gl/forms/gNgTYRTFSZmDjiOB3",
      gPlaceId: ""
    },
    {
      name: "Bistro Dida",
      address: "Šetalište Frana Kršinića 44",
      city: "Korčula",
      category: "Restoran",
      tags: "Kafić i restoran,Restoran morske hrane,Restoran sirove hrane,Suši restoran",
      hours: { sunday: "10:00-00:00", monday: "10:00-00:00", tuesday: "10:00-00:00", wednesday: "10:00-00:00", thursday: "10:00-00:00", friday: "10:00-00:00", saturday: "10:00-00:00" },
      maxCapacity: 70,
      description: "<p>Great food with a super view of the harbour.</p>\n\n<p>Discover the essence of Mediterranean cuisine at Restaurant Dida. Nestled near Park Foretic, this gem offers a delightful culinary journey. Savor the taste of the sea with exceptional octopus salads, tuna, and grilled squid. Indulge in sweet perfection with their tasty parfait. Pair your meal with a glass of their highly-rated white wine. Known for its warm hospitality and affordable prices, Dida boasts a spectacular ambiance.</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/didakorcula",
      gPlaceId: ""
    },
    {
      name: "Restoran Primi Piatti",
      address: "Pavla Rossa 1",
      city: "Hvar",
      category: "Restoran",
      tags: "Agencija za iznajmljivanje automobila,Agencija za osiguranje automobila,Automehaničarska radionica,Automehaničarska radionica,Automobilske usluge,Dobavljač dijelova za autolimariju,Prodavaonica autodijelova,Prodavaonica automobilske opreme",
      hours: { sunday: "16:00-22:00", monday: "16:00-22:00", tuesday: "16:00-22:00", wednesday: "16:00-22:00", thursday: "16:00-22:00", friday: "16:00-22:00", saturday: "16:00-22:00" },
      maxCapacity: 20,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/pscopel",
      gPlaceId: ""
    },
    {
      name: "Adriatic Sushi & Oyster Bar Split",
      address: "Carrarina poljana 4",
      city: "Split",
      category: "Restoran",
      tags: "",
      hours: { sunday: "12:00-23:30", monday: "12:00-23:30", tuesday: "12:00-23:30", wednesday: "12:00-23:30", thursday: "12:00-23:30", friday: "12:00-23:30", saturday: "12:00-23:30" },
      maxCapacity: 50,
      description: "<p><strong>Sushi meets Dalmatia in the heart of Split.</strong> Enjoy authentic Japanese and modern Croatian cuisine in a stunning historical setting. Let your taste buds embark on an unforgettable journey.</p>",
      bookingLink: "https://bookyour.smokvina.hr/b/asobs",
      gPlaceId: ""
    },
    {
      name: "Wine & Food bar Bokar",
      address: "Ulica Sv. Roka 15",
      city: "Korčula",
      category: "Restoran",
      tags: "Kafić i restoran,Restoran morske hrane,Restoran s mesnim jelima,Vinarija,Vinski bar",
      hours: { sunday: "12:00-00:00", monday: "12:00-00:00", tuesday: "12:00-00:00", wednesday: "12:00-00:00", thursday: "12:00-00:00", friday: "12:00-00:00", saturday: "12:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/wfbb",
      gPlaceId: ""
    },
    {
      name: "Pizzeria Fabio",
      address: "Ulica Poljičkih knezova 1",
      city: "Podstrana",
      category: "Pizzerija",
      tags: "",
      hours: { sunday: "07:00-23:30", monday: "07:00-23:30", tuesday: "07:00-23:30", wednesday: "07:00-23:30", thursday: "07:00-23:30", friday: "07:00-23:30", saturday: "07:00-23:30" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/o/pfp",
      gPlaceId: ""
    },
    {
      name: "Restaurant - pizzeria Doris",
      address: "Punta Jurana 1",
      city: "Korčula",
      category: "Restoran",
      tags: "Mesni restoran,Pizzerija,Restoran brze prehrane",
      hours: { sunday: "07:00-00:00", monday: "07:00-00:00", tuesday: "07:00-00:00", wednesday: "07:00-00:00", thursday: "07:00-00:00", friday: "07:00-00:00", saturday: "07:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/pizzeriadoriskor",
      gPlaceId: ""
    },
    {
      name: "Konoba Aurora",
      address: "Šetalište Petra Kanavelića 6",
      city: "Korčula",
      category: "Restoran",
      tags: "Restoran morske hrane,Restoran s jelima s roštilja,Restoran zdrave prehrane",
      hours: { sunday: "08:00-00:00", monday: "08:00-00:00", tuesday: "08:00-00:00", wednesday: "08:00-00:00", thursday: "08:00-00:00", friday: "08:00-00:00", saturday: "08:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/konobaaurora",
      gPlaceId: ""
    },
    {
      name: "Restoran Agape",
      address: "Franjevačkih mučenika 12",
      city: "Međugorje",
      category: "Restoran",
      tags: "Hotel",
      hours: { sunday: "08:00-23:00", monday: "08:00-23:00", tuesday: "08:00-23:00", wednesday: "08:00-23:00", thursday: "08:00-23:00", friday: "08:00-23:00", saturday: "08:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/agape",
      gPlaceId: ""
    },
    {
      name: "Vrilo",
      address: "Vrilo 2",
      city: "Postira",
      category: "Hotel",
      tags: "",
      hours: { sunday: "", monday: "", tuesday: "", wednesday: "", thursday: "", friday: "", saturday: "" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://goo.gl/forms/rn8d2bgPADJLidmL2",
      gPlaceId: ""
    },
    {
      name: "Restoran Duje",
      address: "Ulica slobode 16a",
      city: "Split",
      category: "Restoran",
      tags: "",
      hours: { sunday: "11:00-17:00", monday: "11:00-23:00", tuesday: "11:00-23:00", wednesday: "11:00-23:00", thursday: "11:00-23:00", friday: "11:00-23:00", saturday: "11:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/o/prodmb",
      gPlaceId: ""
    },
    {
      name: "Black Island Winery",
      address: "Smokvica 295",
      city: "Smokvica, Korčula",
      category: "Restoran",
      tags: "Vinarija",
      hours: { sunday: "11:00-17:00", monday: "08:00-20:00", tuesday: "08:00-20:00", wednesday: "08:00-20:00", thursday: "08:00-20:00", friday: "08:00-21:00", saturday: "09:00-21:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/blackisland",
      gPlaceId: ""
    },
    {
      name: "Kod Kapetana",
      address: "Fabrika 30",
      city: "Hvar",
      category: "Restoran",
      tags: "Restoran morske hrane",
      hours: { sunday: "15:00 - 00:00", monday: "15:00 - 00:00", tuesday: "15:00 - 00:00", wednesday: "15:00 - 00:00", thursday: "15:00 - 00:00", friday: "15:00 - 00:00", saturday: "15:00 - 00:00" },
      maxCapacity: 50,
      description: "Our restaurant, with its rich offer of traditional fish specialties prepared on the old recipes and meat specialties and a beautiful view of Hvar's shore from our terrace, attracts many satisfied guests who are always returning back. High quality service and the rich offer of the local wines.",
      bookingLink: "https://smokvina.hr/bookyour/r/kkhr",
      gPlaceId: ""
    },
    {
      name: "Plava Alga",
      address: "Obala Riva 29",
      city: "Hvar",
      category: "Restoran",
      tags: "Restoran morske hrane",
      hours: { sunday: "12:00-00:00", monday: "12:00-00:00", tuesday: "12:00-00:00", wednesday: "12:00-00:00", thursday: "12:00-00:00", friday: "12:00-00:00", saturday: "12:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://bookyour.smokvina.hr/r/plavaalga",
      gPlaceId: ""
    },
    {
      name: "Konoba Tramonto",
      address: "Ismaelli Ul 12",
      city: "Korčula",
      category: "Restoran",
      tags: "",
      hours: { sunday: "09:00-00:00", monday: "09:00-00:00", tuesday: "09:00-00:00", wednesday: "09:00-00:00", thursday: "09:00-00:00", friday: "09:00-00:00", saturday: "09:00-00:00" },
      maxCapacity: 50,
      description: "Located in Korcula, great atmosphere, family owned restaurant, spectacular views overlooking the area.",
      bookingLink: "https://smokvina.hr/bookyour/r/ktk",
      gPlaceId: ""
    },
    {
      name: "Điron",
      address: "Gruda 96, 20215, Gruda, Hrvatska",
      city: "Gruda",
      category: "Bistro",
      tags: "",
      hours: { sunday: "Closed", monday: "10:00-17:00", tuesday: "10:00-17:00", wednesday: "10:00-17:00", thursday: "10:00-17:00", friday: "10:00-17:00", saturday: "10:00-17:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/diron",
      gPlaceId: ""
    },
    {
      name: "Restoran Kopun",
      address: "Poljana Ruđera Boškovića 7",
      city: "Dubrovnik",
      category: "Restoran",
      tags: "Konoba",
      hours: { sunday: "09:00-22:00", monday: "09:00-22:00", tuesday: "09:00-22:00", wednesday: "09:00-22:00", thursday: "09:00-22:00", friday: "09:00–22:00", saturday: "09:00–22:00" },
      maxCapacity: 50,
      description: "Here at restaurant Kopun we take great pride at our efforts to bring back some of the old Croatian recipes handed down through centuries. Rich history of our country is a perfect place to search for variety in cuisine as Croatia is incredibly diverse country despite relatively small territorry it encompasses. This diversity developed throughout the turbulent history of this country fueled by a myriad of different cultural influences that we as a people came in touch with. It's time to explore...",
      bookingLink: "https://smokvina.hr/bookyour/r/kopun",
      gPlaceId: ""
    },
    {
      name: "Restoran & Lounge Bar Vespera",
      address: "Riva 21",
      city: "Stari Grad",
      category: "Restoran",
      tags: "Bar",
      hours: { sunday: "08:00-22:00", monday: "08:00-22:00", tuesday: "08:00-22:00", wednesday: "08:00-22:00", thursday: "08:00-22:00", friday: "08:00-22:00", saturday: "08:00-22:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/vespera",
      gPlaceId: ""
    },
    {
      name: "Trattoria Tinel",
      address: "Ulica Tomića stine 1",
      city: "Split",
      category: "restoran",
      tags: "",
      hours: { sunday: "08:00-00:00", monday: "08:00-00:00", tuesday: "08:00-00:00", wednesday: "08:00-00:00", thursday: "08:00-00:00", friday: "08:00-00:00", saturday: "08:00-00:00" },
      maxCapacity: 150,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/tinelsplit",
      gPlaceId: ""
    },
    {
      name: "Štajun Hvar",
      address: "Težačka 2",
      city: "Hvar",
      category: "restoran",
      tags: "",
      hours: { sunday: "12:00-00:00", monday: "12:00-00:00", tuesday: "12:00-00:00", wednesday: "12:00-00:00", thursday: "12:00-00:00", friday: "12:00-00:00", saturday: "12:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://bookyour.smokvina.hr/b/stajunhvar",
      gPlaceId: ""
    },
    {
      name: "Ciribiribela",
      address: "Plinarska ul. 6",
      city: "Split",
      category: "restoran",
      tags: "",
      hours: { sunday: "07:30–00:00", monday: "", tuesday: "07:30–00:00", wednesday: "07:30–00:00", thursday: "07:30–00:00", friday: "07:30–00:00", saturday: "07:30–00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "",
      gPlaceId: ""
    },
    {
      name: "Konoba Kod Pjera Split",
      address: "Šetalište Kalafata 2",
      city: "Split",
      category: "Restoran",
      tags: "",
      hours: { sunday: "08:00-23:00", monday: "zatvoreno", tuesday: "08:00-23:00", wednesday: "08:00-23:00", thursday: "08:00-23:00", friday: "08:00-23:00", saturday: "08:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/kodpjera",
      gPlaceId: ""
    },
    {
      name: "Restoran Giaxa",
      address: "Petra Hektorovića 3",
      city: "Hvar",
      category: "Restoran",
      tags: "",
      hours: { sunday: "12:00-00:00", monday: "12:00-00:00", tuesday: "12:00-00:00", wednesday: "12:00-00:00", thursday: "12:00-00:00", friday: "12:00-00:00", saturday: "12:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/giaxa",
      gPlaceId: ""
    },
    {
      name: "Konoba Matuško",
      address: "Dingač borak 25",
      city: "Potomje",
      category: "restoran",
      tags: "",
      hours: { sunday: "12:00-23:00", monday: "12:00-23:00", tuesday: "12:00-23:00", wednesday: "12:00-23:00", thursday: "12:00-23:00", friday: "12:00-23:00", saturday: "12:00-23:00" },
      maxCapacity: 50,
      description: "<p>When it comes to great wines, Croatia&#39;s Peljesac Peninsula doesn&#39;t exactly spring to mind the way Montepulciano or Rioja might. But that doesn&#39;t mean you shouldn&#39;t pay a visit to Peljesac&#39;s family-owned wineries Matusko. The Matusko Winery wines are easily identified by their unique labeling which features the illustration of two donkeys. The wines produced at Matusko Winery are known to be high quality and affordable, making it a popular tourist attraction for the growing wine enthusiast market that is emerging in Croatia. Dingač, matured in silence of oak barrels, with dark ruby red color and purple hues but clear at the same time, it has full and rounded flavor, harmonious taste combining astringency and sweetness. Their smooth and well-balanced Plavac Mali is not only great, but also quite affordable.</p>\n\n<p>As and addition to winery, Restaurant Tavern Matusko will offer you some local dishes served on a lovely terrace perched on the hill above the sea.</p>",
      bookingLink: "https://smokvina.hr/bookyour/r/matuskotavern",
      gPlaceId: ""
    },
    {
      name: "Restaurant Filippi Korcula",
      address: "Šetalište Petra Kanavelića",
      city: "Korcula",
      category: "restaurant",
      tags: "",
      hours: { sunday: "09:00-00:00", monday: "09:00-00:00", tuesday: "09:00-00:00", wednesday: "09:00-00:00", thursday: "09:00-00:00", friday: "09:00-00:00", saturday: "09:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://bookyour.smokvina.hr/r/filippikorcula",
      gPlaceId: ""
    },
    {
      name: "Restoran Aquarius",
      address: "Mala Proversa 3",
      city: "Sali",
      category: "Restoran",
      tags: "",
      hours: { sunday: "09:00 - 23:00", monday: "09:00 - 23:00", tuesday: "09:00 - 23:00", wednesday: "09:00 - 23:00", thursday: "09:00 - 23:00", friday: "09:00 - 23:00", saturday: "09:00 - 23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/aquarius",
      gPlaceId: ""
    },
    {
      name: "Konoba Pizzeria Maslina",
      address: "Teutina 1A",
      city: "Split",
      category: "Pizzerija",
      tags: "",
      hours: { sunday: "12:00 - 23:00", monday: "12:00 - 23:00", tuesday: "12:00 - 23:00", wednesday: "12:00 - 23:00", thursday: "12:00 - 23:00", friday: "12:00 - 23:00", saturday: "12:00 - 23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/maslinasplit",
      gPlaceId: ""
    },
    {
      name: "Museum bar History Split",
      address: "Uvala bacvice",
      city: "Split",
      category: "Bar",
      tags: "",
      hours: { sunday: "10:00 - 00:00", monday: "10:00 - 00:00", tuesday: "10:00 - 00:00", wednesday: "10:00 - 00:00", thursday: "10:00 - 00:00", friday: "10:00 - 00:00", saturday: "10:00 - 00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/b/history",
      gPlaceId: ""
    },
    {
      name: "Puteus Restaurant Brač",
      address: "Trg sv. Jeronima 4",
      city: "Pučišća",
      category: "Restoran",
      tags: "",
      hours: { sunday: "18:00-23:00", monday: "18:00-23:00", tuesday: "18:00-23:00", wednesday: "18:00-23:00", thursday: "18:00-23:00", friday: "18:00-23:00", saturday: "18:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/puteusrest",
      gPlaceId: ""
    },
    {
      name: "Restoran Spalatin",
      address: "Ul. bana Josipa Jelačića 1",
      city: "Split",
      category: "Restoran",
      tags: "Medditeranean food restaurant",
      hours: { sunday: "12:00-23:00", monday: "12:00-23:00", tuesday: "12:00-23:00", wednesday: "12:00-23:00", thursday: "12:00-23:00", friday: "12:00-23:00", saturday: "12:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/spalatinst",
      gPlaceId: ""
    },
    {
      name: "Restaurant Boom Split",
      address: "Nigerova 2",
      city: "Split",
      category: "Restoran",
      tags: "",
      hours: { sunday: "12:00-23:00", monday: "12:00-23:00", tuesday: "12:00-23:00", wednesday: "12:00-23:00", thursday: "12:00-23:00", friday: "12:00-23:00", saturday: "12:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/boom",
      gPlaceId: ""
    },
    {
      name: "Wine bar Roco",
      address: "Ul. Don Jakova Salečića",
      city: "Korčula",
      category: "Vinski bar",
      tags: "",
      hours: { sunday: "15:00 - 00:00", monday: "15:00 - 00:00", tuesday: "15:00 - 00:00", wednesday: "15:00 - 00:00", thursday: "15:00 - 00:00", friday: "15:00 - 00:00", saturday: "15:00 - 00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://bookyour.smokvina.hr/b/winebarroco",
      gPlaceId: ""
    },
    {
      name: "Restoran Marijan",
      address: "Zagrebačka 4",
      city: "Vodice",
      category: "Restoran",
      tags: "",
      hours: { sunday: "07:00-00:00", monday: "07:00-00:00", tuesday: "07:00-00:00", wednesday: "07:00-00:00", thursday: "07:00-00:00", friday: "07:00-00:00", saturday: "07:00-00:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/restaurantmarijan",
      gPlaceId: ""
    },
    {
      name: "Restaurant Tiffany Split",
      address: "Poljana kraljice Jelene 5",
      city: "Split",
      category: "restoran",
      tags: "",
      hours: { sunday: "07:00 - 23:00", monday: "07:00 - 23:00", tuesday: "07:00 - 23:00", wednesday: "07:00 - 23:00", thursday: "07:00 - 23:00", friday: "07:00 - 23:00", saturday: "07:00 - 23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://bookyour.smokvina.hr/b/tiffany",
      gPlaceId: ""
    },
    {
      name: "Restaurant Vicko",
      address: "Donje polje 61",
      city: "Šibenik",
      category: "Lamb restaurant",
      tags: "",
      hours: { sunday: "08:00-23:00", monday: "08:00-23:00", tuesday: "08:00-23:00", wednesday: "08:00-23:00", thursday: "08:00-23:00", friday: "08:00-23:00", saturday: "08:00-23:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "www.superba.hr",
      gPlaceId: ""
    },
    {
      name: "Jurlinovi dvori",
      address: "43.610188, 15.973579",
      city: "Primošten Burnji",
      category: "Family restaurant",
      tags: "",
      hours: { sunday: "09:00-22:00", monday: "09:00-22:00", tuesday: "09:00-22:00", wednesday: "09:00-22:00", thursday: "09:00-22:00", friday: "09:00-22:00", saturday: "09:00-22:00" },
      maxCapacity: 50,
      description: "Awesome traditional experience in the beautiful countryside, away from the throngs of people. The whole atmosphere and experience is well worth the drive. Fresh food, wine, and olive oil, locally sourced make for a meal unlike any you can get anywhere else. Run by a retired Roman catholic priest who was born on the same property, the property is like returning to the late 19th century, but with modern toilets. Highly recommend to anyone who wants to experience more than the regular tourist affair.",
      bookingLink: "https://smokvina.hr/bookyour/r/jurlinovidvori",
      gPlaceId: ""
    },
    {
      name: "U.O.Konoba kod Joze",
      address: "Sredmanuška ul. 4",
      city: "Split",
      category: "Restaurant",
      tags: "Fish restaurant",
      hours: { sunday: "12:00-00:00", monday: "10:00-00:00", tuesday: "10:00-00:00", wednesday: "10:00-00:00", thursday: "10:00-00:00", friday: "10:00-00:00", saturday: "12:00-00:00" },
      maxCapacity: 50,
      description: "<p>After exploring Live Museum Split, indulge in a delightful meal at nearby Kod Jose. Savor the exquisite flavors of seafood risotto, black risotto, and shrimp skewers. Complete your dining experience with a heavenly semifreddo, banana split, or pancakes. Enjoy delicious house wine, white wine, or beer in a cozy atmosphere. With friendly service, affordable prices, and charming decor, Kod Jose is a must-visit.</p>\n\n<p><strong>Famus of PEKA - veal or octopus traditonal meal is prepared only on pre reservationa and for 4 person minimum.</strong></p>",
      bookingLink: "https://smokvina.hr/bookyour/r/kodjoze",
      gPlaceId: ""
    },
    {
      name: "Restaurant Piccolo Zagreb",
      address: "ZELENJAK 46",
      city: "Zagreb",
      category: "Restaurant",
      tags: "",
      hours: { sunday: "12:00-18:00", monday: "10:00-22:00", tuesday: "10:00-22:00", wednesday: "10:00-22:00", thursday: "10:00-22:00", friday: "10:00-22:00", saturday: "10:00-22:00" },
      maxCapacity: 50,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/piccolozg",
      gPlaceId: ""
    },
    {
      name: "Anona Split",
      address: "Ulica Mile Gojsalić 1",
      city: "Split",
      category: "Restoran",
      tags: "",
      hours: { sunday: "12:00-23:00", monday: "12:00-23:00", tuesday: "12:00-23:00", wednesday: "12:00-23:00", thursday: "12:00-23:00", friday: "12:00-23:00", saturday: "12:00-23:00" },
      maxCapacity: 20,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/anonasplit",
      gPlaceId: ""
    },
    {
      name: "Arguola sandwich bar",
      address: "Ulica Vladimira Nazora 6",
      city: "Bol",
      category: "Fast Food",
      tags: "Sandwich bar",
      hours: { sunday: "11:00-2:00", monday: "11:00-2:00", tuesday: "11:00-2:00", wednesday: "11:00-2:00", thursday: "11:00-2:00", friday: "11:00-2:00", saturday: "11:00-2:00" },
      maxCapacity: 20,
      description: "",
      bookingLink: "",
      gPlaceId: ""
    },
    {
      name: "Konoba Pizzeria Tapun",
      address: "Ivana Pavla II,345",
      city: "Kaštel Štafilić",
      category: "Restaurant",
      tags: "Restaurant",
      hours: { sunday: "10:00-00:00", monday: "08:00-00:00", tuesday: "08:00-00:00", wednesday: "08:00-00:00", thursday: "08:00-00:00", friday: "08:00-00:00", saturday: "08:00-00:00" },
      maxCapacity: 260,
      description: "<p><strong>Kr&scaron;tenja, Pričesti, Krizme, Pirevi i vjenčanja do 100 osoba, </strong>Rođendani, <strong>Dječji rođendani sa parkom za djecu</strong>, Proslave, Domjenci, Poslovni sastanci, Grupni ručkovi i večere, Ručkovi i večere za grupe.&nbsp;<strong>Pečenje janjaca i odojaka po narudžbi, </strong>Teleće peke po narudžbi, Oborita riba po narudžbi, Domaća spiza i marende, <strong>Tople marende</strong>, Gotova jela, Pizze iz kru&scaron;ne peći. Sve vrste cateringa, Dostava.</p>\n\n<p><u><strong>Večernje zabave sa uživo glazbom Svaki vikend.</strong></u></p>",
      bookingLink: "https://smokvina.hr/bookyour/r/konobatapun",
      gPlaceId: ""
    },
    {
      name: "Restaurant Laf",
      address: "Mažuranićevo šetalište 10",
      city: "Split",
      category: "RESTAURANT",
      tags: "",
      hours: { sunday: "8-22", monday: "8-22", tuesday: "8-22", wednesday: "8-22", thursday: "8-22", friday: "8-22", saturday: "8-22" },
      maxCapacity: 200,
      description: "",
      bookingLink: "",
      gPlaceId: ""
    },
    {
      name: "MB Sveti Šime II",
      address: "Obala kralja Petra Krešimira IV",
      city: "Biograd na Moru",
      category: "Brod za turističke obliaske",
      tags: "",
      hours: { sunday: "08:00-18:00", monday: "08:00-18:00", tuesday: "08:00-18:00", wednesday: "08:00-18:00", thursday: "08:00-18:00", friday: "08:00-18:00", saturday: "08:00-18:00" },
      maxCapacity: 150,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/t/brodsvetisime",
      gPlaceId: ""
    },
    {
      name: "Konoba Pupo",
      address: "Miha Pracata 8",
      city: "Dubrovnik",
      category: "Restoran",
      tags: "",
      hours: { sunday: "08:00-23:00", monday: "08:00-23:00", tuesday: "08:00-23:00", wednesday: "08:00-23:00", thursday: "08:00-23:00", friday: "08:00-23:00", saturday: "08:00-23:00" },
      maxCapacity: 200,
      description: "",
      bookingLink: "https://smokvina.hr/bookyour/r/konobapupo",
      gPlaceId: ""
    }
  ];

  constructor() { }

  getRestaurants(): Restaurant[] {
    return this.restaurants;
  }
}
